'use strict';

// Banco de perguntas — Engenharia de Requisitos
// type 'class' -> classificar a sentença em RF / RNF / RN
// type 'mc'    -> múltipla escolha comum (4 alternativas)

const CLASS_OPTS = ['Requisito Funcional', 'Requisito Não Funcional', 'Regra de Negócio'];

const c = (q, ans, exp) => ({ type: 'class', q, opts: CLASS_OPTS, ans, exp });
const m = (q, opts, ans, exp) => ({ type: 'mc', q, opts, ans, exp });

// ans: 0 = RF, 1 = RNF, 2 = RN
const QUESTIONS = [
  // ---------- Requisitos Funcionais ----------
  c('O sistema deve permitir que o usuário redefina sua senha através de um link enviado por e-mail.', 0,
    'Descreve uma AÇÃO que o sistema executa para o usuário. O que o sistema FAZ = Requisito Funcional.'),
  c('O sistema deve emitir a nota fiscal eletrônica ao final de cada compra concluída.', 0,
    'É uma funcionalidade concreta entregue pelo sistema — emitir NF-e. Comportamento observável = RF.'),
  c('O sistema deve exportar o relatório de vendas nos formatos PDF e CSV.', 0,
    'Exportar relatório é uma função do sistema. Cuidado: o formato não transforma isso em RNF, ele só detalha a função.'),
  c('O aplicativo deve permitir login utilizando conta Google (OAuth).', 0,
    'Autenticar via Google é uma funcionalidade oferecida ao usuário. O "como" (OAuth) é detalhe da mesma função.'),
  c('O sistema deve enviar notificação push sempre que o pedido mudar de status.', 0,
    'Disparar notificação é uma ação executada pelo sistema em resposta a um evento = RF.'),
  c('O sistema deve permitir o cadastro de produtos com nome, preço, categoria e foto.', 0,
    'Um clássico CRUD: cadastrar é função do sistema. Os campos apenas descrevem a entrada dessa função.'),
  c('O sistema deve exibir o histórico de pedidos do cliente dos últimos 12 meses.', 0,
    'Consultar/exibir informação é comportamento do sistema = RF. (O recorte de 12 meses vem de uma regra de negócio, mas a sentença descreve a função.)'),
  c('O gestor deve poder aprovar ou rejeitar solicitações de férias pelo painel.', 0,
    'Aprovar/rejeitar é uma operação que o sistema disponibiliza a um perfil de usuário = RF.'),
  c('O sistema deve permitir buscar clientes por CPF, nome ou e-mail.', 0,
    'Busca é funcionalidade. Se a sentença falasse do TEMPO da busca, aí sim seria não funcional.'),
  c('O sistema deve gerar boleto bancário para pagamento do pedido.', 0,
    'Gerar boleto é uma função entregue ao usuário = RF.'),

  // ---------- Requisitos Não Funcionais ----------
  c('A busca de produtos não deve ultrapassar 2 segundos de resposta em 95% das requisições.', 1,
    'Fala de DESEMPENHO — a qualidade com que a função roda, não a função em si = RNF.'),
  c('O sistema deve estar disponível 99,9% do tempo, medido mensalmente.', 1,
    'Disponibilidade (SLA) é atributo de qualidade do sistema = RNF.'),
  c('As senhas dos usuários devem ser armazenadas com hash bcrypt e nunca em texto puro.', 1,
    'Segurança é atributo de qualidade. Descreve COMO o dado é protegido, não uma função do usuário = RNF.'),
  c('A interface deve ser compatível com leitores de tela, atendendo à WCAG 2.1 nível AA.', 1,
    'Acessibilidade = atributo de qualidade da interface = RNF.'),
  c('O sistema deve suportar 10.000 usuários simultâneos sem degradação perceptível.', 1,
    'Escalabilidade / capacidade de carga = RNF.'),
  c('O back-end deve ser desenvolvido em Java 17 e executado em contêineres Docker.', 1,
    'Restrição tecnológica imposta ao projeto. Restrições entram como RNF (também chamadas de requisitos de restrição).'),
  c('O aplicativo deve funcionar em Android 10 ou superior e iOS 15 ou superior.', 1,
    'Compatibilidade / portabilidade = atributo de qualidade = RNF.'),
  c('Os dados devem trafegar criptografados usando TLS 1.3 em todas as integrações.', 1,
    'Segurança da comunicação — como o sistema se comporta, não o que ele faz para o usuário = RNF.'),
  c('O sistema deve se recuperar de uma falha total em até 15 minutos (RTO de 15 min).', 1,
    'Confiabilidade / recuperação de desastre = RNF.'),
  c('Um usuário novo deve concluir seu primeiro cadastro em no máximo 3 passos.', 1,
    'Usabilidade — mede a facilidade de uso, não uma nova função = RNF.'),
  c('O código deve manter cobertura mínima de 80% em testes automatizados.', 1,
    'Manutenibilidade / qualidade interna do produto = RNF.'),

  // ---------- Regras de Negócio ----------
  c('Clientes com mais de 3 parcelas em atraso não podem realizar novas compras a prazo.', 2,
    'É uma política DA EMPRESA. Existiria mesmo sem sistema — o software apenas a implementa = Regra de Negócio.'),
  c('O desconto máximo que um vendedor pode conceder é de 10% sobre o preço de tabela.', 2,
    'Política/limite definido pelo negócio, independente de tecnologia = RN.'),
  c('Um colaborador só pode solicitar férias após completar 12 meses de contrato.', 2,
    'Vem da CLT / política de RH, não do software = RN. (A tela de solicitar férias é que seria o RF.)'),
  c('O frete é gratuito para pedidos com valor acima de R$ 199,00.', 2,
    'Condição comercial definida pelo negócio = RN. O cálculo do frete na tela seria o RF correspondente.'),
  c('Somente maiores de 18 anos podem abrir conta na plataforma.', 2,
    'Restrição legal/de negócio sobre quem pode ser cliente = RN.'),
  c('A comissão do vendedor corresponde a 5% do valor líquido da venda.', 2,
    'Fórmula definida pela política comercial da empresa = RN.'),
  c('Um pedido só pode ser cancelado enquanto estiver no status "Aguardando envio".', 2,
    'Restringe QUANDO uma operação é válida, segundo a política da empresa = RN.'),
  c('O limite de crédito inicial é de até 3 vezes a renda mensal comprovada.', 2,
    'Critério de concessão de crédito definido pelo negócio = RN.'),
  c('Cada turma pode ter no máximo 40 alunos matriculados.', 2,
    'Limite institucional, não uma função nem um atributo de qualidade = RN.'),
  c('A reserva é cancelada automaticamente se o pagamento não for confirmado em 30 minutos.', 2,
    'A política dos 30 minutos é do negócio. O cancelamento automático é o RF que a implementa.'),
  c('Nenhum item pode ser vendido por valor abaixo do preço de custo.', 2,
    'Regra de precificação da empresa = RN.'),

  // ---------- Múltipla escolha ----------
  m('Qual das alternativas é um requisito NÃO funcional?',
    ['O sistema deve permitir exportar o relatório em PDF.',
     'O sistema deve processar até 500 transações por segundo.',
     'O sistema deve cadastrar novos fornecedores.',
     'O sistema deve enviar e-mail de confirmação de pedido.'], 1,
    'Só a alternativa de 500 TPS fala de desempenho (COMO o sistema se comporta). As demais descrevem funções.'),
  m('Qual é a melhor definição de Regra de Negócio?',
    ['Uma restrição de tecnologia imposta pela equipe de infraestrutura.',
     'Uma política, condição ou cálculo do domínio que existe independentemente do software.',
     'Uma tela que o sistema deve exibir ao usuário final.',
     'Um índice de qualidade medido após o sistema entrar em produção.'], 1,
    'Regra de negócio nasce no domínio (empresa, lei, mercado). O software apenas a automatiza.'),
  m('"O sistema deve calcular o valor do frete." + "O frete é grátis acima de R$ 199." Como classificar cada trecho?',
    ['Ambos são requisitos funcionais.',
     'O primeiro é RF; o segundo é regra de negócio.',
     'O primeiro é regra de negócio; o segundo é RNF.',
     'Ambos são regras de negócio.'], 1,
    'Calcular o frete é a FUNÇÃO. A condição de gratuidade é a POLÍTICA do negócio que alimenta essa função.'),
  m('Qual técnica NÃO é uma técnica de elicitação de requisitos?',
    ['Entrevista com stakeholders', 'Prototipação', 'Teste de carga (stress test)', 'Observação / etnografia'], 2,
    'Teste de carga é uma técnica de VERIFICAÇÃO/validação de um RNF, executada depois — não serve para levantar requisitos.'),
  m('Um requisito bem escrito deve ser, principalmente:',
    ['Extenso e cheio de detalhes técnicos de implementação.',
     'Ambíguo, para dar liberdade ao time de desenvolvimento.',
     'Claro, verificável, viável e sem ambiguidade.',
     'Escrito somente pelo desenvolvedor responsável.'], 2,
    'Requisito precisa ser testável e não ambíguo. "O sistema deve ser rápido" é ruim; "responder em até 2s" é verificável.'),
  m('"O sistema deve ser rápido e amigável." Qual o principal defeito desse requisito?',
    ['Está na categoria errada.', 'Não é verificável — falta critério mensurável.',
     'É longo demais.', 'Deveria ser uma regra de negócio.'], 1,
    'Sem métrica não há como testar. O correto seria "responder em até 2s em 95% das requisições".'),
  m('Na engenharia de requisitos, o documento que descreve requisitos na linguagem do CLIENTE é:',
    ['Especificação de requisitos de software (SRS)', 'Documento de requisitos do usuário',
     'Diagrama de classes', 'Plano de testes'], 1,
    'Requisitos do usuário: linguagem natural, foco no cliente. A SRS é a versão detalhada para a equipe técnica.'),
  m('Qual destes é um requisito funcional?',
    ['O sistema deve garantir integridade dos dados mesmo em queda de energia.',
     'O sistema deve permitir o agendamento de consultas com escolha de médico e horário.',
     'O sistema deve ser auditado trimestralmente por empresa externa.',
     'O tempo de treinamento de um novo operador não deve passar de 4 horas.'], 1,
    'Agendar consulta é uma ação do sistema para o usuário. As demais falam de qualidade, processo ou usabilidade.'),
  m('A rastreabilidade de requisitos serve para:',
    ['Escolher a linguagem de programação do projeto.',
     'Ligar cada requisito à sua origem e aos artefatos que o implementam e testam.',
     'Medir a performance da aplicação em produção.',
     'Definir o preço final do software para o cliente.'], 1,
    'Rastreabilidade conecta origem → requisito → código → teste, permitindo avaliar impacto de mudanças.'),
  m('"Apenas gerentes podem aprovar despesas acima de R$ 5.000." Isso é:',
    ['Requisito não funcional de segurança', 'Regra de negócio',
     'Requisito funcional de interface', 'Restrição tecnológica'], 1,
    'A alçada de aprovação é política da empresa. O controle de acesso que a implementa é que envolve RF/RNF.'),
];

module.exports = { QUESTIONS, CLASS_OPTS };
